repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: local
  hooks:
  - id: shellcheck
    name: ShellCheck
    description: This hook applies ShellCheck to scripts in bin.
    language: system
    entry: shellcheck --shell=bash
    exclude: ^(.gitignore|.gitmodules|.pre-commit-config.yaml|LICENSE|README.md)$
