#!/bin/bash
#
# @(#) Prints 8/16 color chart.
#
# Copyright (c) 2013 Shinya Ishida. All rights reserved.
#
#
#  Fg code | Bg code |    Color
# ---------+---------+--------------
#       30 |      40 | black
#       31 |      41 | red
#       32 |      42 | geen
#       33 |      43 | brown
#       34 |      44 | blue
#       35 |      45 | purple
#       36 |      46 | cyan
#       37 |      47 | light gray
#       39 |      49 | (default)
#       90 |     100 | dark gray
#       91 |     101 | light red
#       92 |     102 | light green
#       93 |     103 | yellow
#       94 |     104 | light blue
#       95 |     105 | light purple
#       96 |     106 | light cyan
#       97 |     107 | white
#
#    Set   |  Reset  |    Effect
# ---------+---------+---------------
#      n/a |       0 | (no effect)
#        1 |      21 | bold/blight
#        2 |      22 | dim
#        4 |      24 | underline
#        5 |      25 | blink
#        7 |      27 | invert
#        8 |      28 | hide
#

readonly ME=$0
readonly AVAIL_EFFECTS=(0 1 2 4 5 7 8)
AVAIL_FOREGROUNDS=(39 {30..37} {90..97})
AVAIL_BACKGROUNDS=(49 {40..47} {100..107})
readonly HEADER='ef;fg\bg'$(for i in ${AVAIL_BACKGROUNDS[@]}; do
				[[ ${#i} == 2 ]] && echo -n "      $i" || echo -n "     $i"
			    done)

function __PrintUsage() {
    cat <<EOF
Usage:
  $(basename ${ME}) [<effect code> [<effect code>]]
  $(basename ${ME}) -h
Note:
  - Available foreground effects are 0, 1, 2, 4, 5, 7, and 8.
  - If effect code is omitted, whole color chart with all possible effects is printed.
EOF
}

function __PrintColorChart() {
    local fg_eff=$1
    echo "${HEADER}"
    for fg_color in ${AVAIL_FOREGROUNDS[@]}; do
	fg="${fg_eff};${fg_color}"
	echo -ne "${fg}\t"
	for bg_color in ${AVAIL_BACKGROUNDS[@]}; do
	    echo -ne "\\033[${fg};${bg_color}m Sample "
	done
	echo -e "\033[0m"
    done
}
readonly -f __PrintColorChart


SEQ=$(which seq >/dev/null && which seq) || \
    SEQ=$(which gseq >/dev/null && which gseq) || \
    (echo "seq/gseq not installed" && exit 1)

while getopts "h" flag; do
    case $flag in
	h)
	    __PrintUsage
	    exit 0
	    ;;
	*)
	    __PrintUsage
	    exit 1
	    ;;
    esac
done

effects=(${*-${AVAIL_EFFECTS[@]}})
for fg_eff in ${effects[@]}; do
    [[ ${fg_eff} =~ ^[0124578]$ ]] && __PrintColorChart ${fg_eff}
done
