#!/usr/bin/env bash
#
# @(#) Prints a gauge to indicate column numbers.
#
# Copyright (c) 2013 Shinya Ishida. All rights reserved.
#

readonly DEFAULT_LENGTH=80

function __PrintUsage() {
    cat <<EOF
usage:
    $(basename "$0") [-h] [-t type] [length]
options:
    -t type    gauge type (full, even, five, or ten; even by default)
    -h         print this help
note:
    If 'length' is omitted, the default length ($DEFAULT_LENGTH) is used.
EOF
}
readonly -f __PrintUsage

function __GetGaugeTemplate() {
    local -r gauge_full='123456789'
    local -r gauge_even=${gauge_full//[13579]/ }
    local -r gauge_default=${gauge_even}
    local -r gauge_template_name="gauge_$1"
    local selected_gauge=${!gauge_template_name}
    selected_gauge=${selected_gauge-${gauge_default}}
    echo "${selected_gauge//[0-9]/+}"
}
readonly -f __GetGaugeTemplate

function __PrintGauge() {
    local -r gauge_tmpl=$(__GetGaugeTemplate "$1")
    gauge=""
    local -r dec_count=$(($2 / 10))
    q=0
    while [ $q -lt $dec_count ]; do
	((q++))
	gauge="$gauge$gauge_tmpl$((q % 10))"
    done
    r=$(($2 % 10))
    if [ $r -gt 0 ]; then
        gauge="$gauge${gauge_tmpl:0:$((r - 1))}$r"
    fi
    echo "$gauge"
}
readonly -f __PrintGauge

#
# Main routine
#

gauge_type=default
while getopts "t:h" flag; do
    case $flag in
	t)
	    gauge_type=$OPTARG;;
	h)
	    __PrintUsage
	    exit 0;;
        *)
            exit 1;;
    esac
done
shift $((OPTIND - 1))

if [[ "$1" =~ ^[0-9]*$ ]]; then
    __PrintGauge "$gauge_type" "${1-$DEFAULT_LENGTH}"
else
    __PrintUsage
    exit 2
fi
