#!/usr/bin/env bash
#
# @(#) Prints a gauge to indicate column numbers.
#
# Copyright (c) 2013 Shinya Ishida. All rights reserved.
#

readonly default_length=80
# shellcheck disable=SC2034
readonly gauge_full='123456789'
# shellcheck disable=SC2034
readonly gauge_even=' 2 4 6 8 '
# shellcheck disable=SC2034
readonly gauge_five='    5    '
# shellcheck disable=SC2034
readonly gauge_ten='         '
readonly gauge_default="${gauge_even}"

function __print_usage {
    cat <<EOF
usage:
    ${0##*/} [-h] [-t type] [length]
options:
    -t type    gauge type (full, even, five, or ten; even by default)
    -h         print this help
note:
    If 'length' is omitted, the default length ($default_length) is used.
EOF
}
readonly -f __print_usage

function __get_gauge_template {
  local -r gauge_template_name="gauge_$1"
  local selected_gauge=${!gauge_template_name}
  selected_gauge=${selected_gauge-${gauge_default}}
  echo "${selected_gauge//[0-9]/+}"
}
readonly -f __get_gauge_template

function __print_gauge {
  local -r gauge_tmpl=$(__get_gauge_template "$1")
  gauge=""
  local -r dec_count=$(($2 / 10))
  q=0
  while [ $q -lt $dec_count ]; do
  	((q++))
	  gauge="$gauge$gauge_tmpl$((q % 10))"
  done
  r=$(($2 % 10))
  if [ $r -gt 0 ]; then
    gauge="$gauge${gauge_tmpl:0:$((r - 1))}$r"
  fi
  echo "$gauge"
}
readonly -f __print_gauge

##### Main routine

gauge_type=default
while getopts "t:h" flag; do
  case $flag in
    t)
	    gauge_type=$OPTARG;;
    h)
	    __print_usage
	    exit 0;;
    *)
      exit 1;;
  esac
done
shift $((OPTIND - 1))

number="${1:-$default_length}"
if [[ "$number" =~ ^[0-9]*$ ]]; then
  __print_gauge "$gauge_type" "$number"
else
  __print_usage
  exit 2
fi

