#!/bin/bash
#
# @(#) Utility to transform arguments into a punctuated sequence.
#
# Copyright (c) 2018 Shinya Ishida. All rights reserved.
#

readonly conj='or'

function __or() {
  case $# in
  	0)
    	;;
	  1)
	    echo "$*";;
	  2)
	    args="$*"
	    echo "${args% *} ${conj} ${args##* }";;
	  *)
	    args="$*"
	    args=${args// /, }
	    echo "${args%,*}, ${conj} ${args##*, }";;
  esac
}
readonly -f __or

if [ -p /dev/stdin ]; then
  __or "$(cat -)"
else
  __or "$@"
fi
