#!/usr/bin/env bash
#
# @(#) Utility to transform numbers into ordinal numbers
#
# Copyright (c) 2018 Shinya Ishida. All rights reserved.
#

function __ord() {
    local digits=${#1}
    local suffix='th'
    if [[ $digits == 1 ]]; then
	case $1 in
	    1)
		suffix='st';;
	    2)
		suffix='nd';;
	    3)
		suffix='rd';;
	esac
    elif [[ ${1: -2:1} =~ ^[0|2-9]$ ]]; then
	case ${1: -1:1} in
            1)
	        suffix='st';;
	    2)
	        suffix='nd';;
	    3)
	        suffix='rd';;
	esac
    fi
    echo "$1$suffix"
}
readonly -f __ord

function __ords() {
    local a=()
    local i=0
    for n in "$@"; do
	if [[ $n =~ ^0|[1-9][0-9]*$ ]]; then
	    a[$i]=$(__ord "$n")
        else
	    a[$i]="$n"
        fi
	((i+=1))
    done
    echo "${a[@]}"
}
readonly -f __ords

if [ -p /dev/stdin ]; then
    __ords "$(cat -)"
else
    __ords "$@"
fi
